import type { Metadata } from "next";
import { Karla, Roboto } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/context/UserContext";
import { createClient } from "@/lib/supabase-server";
import { buscarProfilePorId } from "@/services/profile.service";

const roboto = Roboto({
	variable: "--font-roboto",
	subsets: ["latin"],
	weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const supabase = createClient();
	const {
		data: { session },
	} = await supabase.auth.getSession();

	let profile = undefined;
	if (session?.user?.id) {
		const token = session.access_token;
		profile = await buscarProfilePorId(session.user.id, token);
	}

	return (
		<html lang="ptbr" suppressHydrationWarning>
			<body
				suppressHydrationWarning
				className={`${roboto.variable} antialiased bg-background text-foreground`}
			>
				<UserProvider initialProfile={profile}>{children}</UserProvider>
			</body>
		</html>
	);
}
