import type { Metadata } from "next";
import { Karla, Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
	variable: "--font-roboto",
	subsets: ["latin"],
	weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ptbr" suppressHydrationWarning>
			<body
				suppressHydrationWarning
				className={`${roboto.variable} antialiased bg-blizzard-blue text-eerie-black`}
			>
				{children}
			</body>
		</html>
	);
}
